// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleApi.Data;

#nullable disable

namespace VehicleApi.Migrations
{
    [DbContext(typeof(CarContext))]
    [Migration("20250608164015_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarCarEquipment", b =>
                {
                    b.Property<int>("CarEquipmentsId")
                        .HasColumnType("int");

                    b.Property<int>("CarsId")
                        .HasColumnType("int");

                    b.HasKey("CarEquipmentsId", "CarsId");

                    b.HasIndex("CarsId");

                    b.ToTable("CarCarEquipment");

                    b.HasData(
                        new
                        {
                            CarEquipmentsId = 1,
                            CarsId = 1
                        },
                        new
                        {
                            CarEquipmentsId = 2,
                            CarsId = 1
                        },
                        new
                        {
                            CarEquipmentsId = 1,
                            CarsId = 2
                        });
                });

            modelBuilder.Entity("VehicleApi.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Volvo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BMW"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mercedes-Benz"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Audi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Volkswagen"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tesla"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hyundai"
                        });
                });

            modelBuilder.Entity("VehicleApi.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicensePlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Colour = "Black",
                            LicensePlateNumber = "ABC123",
                            ModelName = "XC90",
                            VIN = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            Colour = "White",
                            LicensePlateNumber = "XYZ789",
                            ModelName = "Corolla",
                            VIN = "987654321"
                        });
                });

            modelBuilder.Entity("VehicleApi.Models.CarEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CarEquipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Leather Seats"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sunroof"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bluetooth"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Backup Camera"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cruise Control"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Heated Seats"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Navigation System"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Keyless Entry"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Parking Sensors"
                        });
                });

            modelBuilder.Entity("CarCarEquipment", b =>
                {
                    b.HasOne("VehicleApi.Models.CarEquipment", null)
                        .WithMany()
                        .HasForeignKey("CarEquipmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleApi.Models.Car", null)
                        .WithMany()
                        .HasForeignKey("CarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VehicleApi.Models.Car", b =>
                {
                    b.HasOne("VehicleApi.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("VehicleApi.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
